### ISSUE TITLE
[GSoC 2022] SANTé API enhancement

### ISSUE THREAD

**Issue by edgardmarx** [LiberAI/gsoc#2]
# Introduction
[SANTé](https://github.com/LiberAI/sante) aims at building an end-to-end system to faciliate information navigation, exploration and seeking through  RDF Knowledge bases with natural language queries.

There are several knowledge bases currently published in RDF format and exploring this information is still challenging for non-RDF neither SPARQL users. This GSoC project consists of enhancing SANTé's APIs by including tests, benchmakrs and additional functionalities.

# Documentation
## Reading Material
Read the current papers on which SANTe is built upon as well as the repository:

### Papers

- SANTé: A Light-Weight End-to-End Semantic Search Framework for RDF Data: https://link.springer.com/chapter/10.1007/978-3-030-80418-3_17

- Exploring Term Networks for Semantic Search over RDF Knowledge Graphs: https://link.springer.com/chapter/10.1007/978-3-319-49157-8_22

### Repository:

- https://github.com/LiberAI/sante

# Warm-up tasks
Fork the project and start by instantiating your own instance using one of the standards data sets such as FOAF ontology or Pokemon.
Try out the implemented API's: DBpedia Lookup, Reconcile, Search  and Suggest (check the repository).
Read the APIs specifications:

- Reconciliation: https://reconciliation-api.github.io/specs/latest/
- DBpedia lookup: https://github.com/dbpedia/dbpedia-lookup

# Your proposal
Now that you have a good understanding of the current state of the project, we suggest you to build proposals pondering on some of the following points, feel free to bring your own solutions to tackle the problems that the project faces.

How the current APIs can be further enhanced?

Which other APIs can be integrated?

Which benchmarks and measures can be used to evaluate the results' accuracy?

# Additional information

- Project size: 175h or 350h
- Difficulty: medium

# Mentors
@edgardmarx, TBD

Feel free to contact us for more information. We eagerly look forward to working with you and contributing towards making data accessible to all.

**Comment by mommi84** [comment]
Liber AI was not accepted to GSoC 2022, however contributors may still apply via DBpedia at the following link:
* https://forum.dbpedia.org/t/dbpedia-search-api-enhancement/1705
